### ISSUE TITLE
Authentication Scheme

### ISSUE THREAD

**Issue by 50L1DU5** [dsr-secure64/nfv-dns-rest-api#1]
### Authentication object referenced, but no scheme exists
This document needs to specify an authentication mechanism so that it may be modeled. This may be (but is certainly not limited to):
- OAuth 1 
- OAuth 2
- JSON Web Tokens (JWT) 
- Custom Headers
- HTTP Basic Authentication
- HTTP Digest Authentication

**Comment by haochih** [comment]
Waiting for answer from PLM to see if authentication mechanism is needed for sDNS.

**Comment by haochih** [comment]
Talked to our PLM (Mandeep) and Vivek (sDNS SE), currently customer does not have requirement for Authentication mechanism, but customer may request for it later.

In Ve-VNFM RESTful APIs,  there is a custom Auth parameter defined for /api/v1.0/sys  that will result in an authenticated session between EMS and the VNF.        sDNS is in core network, and the connection will be secured link (SSL), so I think HTTP Basic Auth may be ok .    

Zeev/Joel et, al., , what do you think?
